name: Automated API tests using Newman

on: push

jobs:
  run-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Create missing directories
        run: |
          mkdir -p _docker/cron

      - name: Start Docker services
        run: docker compose up -d --build

      - name: Wait for services to be ready
        run: sleep 60

      - name: Setup database
        run: |
          docker compose exec -T laravel-api php artisan migrate --force
          docker compose exec -T laravel-api php artisan db:seed --force

      - name: Install Newman
        run: npm install -g newman

      - name: Run Newman with data file
        run: newman run 'tests/api/API Testing.postman_collection.json' --iteration-data 'tests/api/login.json'

      - name: Cleanup Docker
        if: always()
        run: docker compose down
