name: Automated API tests using Newman

on: push

jobs:
  run-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Newman
        run: npm install -g newman

      - name: Run Newman with data file
        run: |
          newman run "./API Testing.postman_collection.json" \
            --iteration-data "./login.json" \
            --reporters cli,json \
            --reporter-json-export "newman-report.json" \
            --suppress-exit-code

      - name: Upload Newman Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: newman-report
          path: newman-report.json
