name: Automated API tests using Newman

on: push

jobs:
  run-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Newman
        run: npm install -g newman

      - name: Run Newman with data file
        run: |
          newman run "./.postman/collection.json" \
            --iteration-data "./.postman/login.json" \
            --reporters cli,json \
            --reporter-json-export "newman-report.json"
